export const IDENTITY_CONSTANTS = {
  ACCESS_TOKEN_TYPE: 'access',
  EMAIL_VERIFY_TOKEN_TYPE: 'email_verify',
  PASSWORD_RESET_TOKEN_TYPE: 'password_reset',
  REFRESH_TOKEN_BYTES: 48,
  SESSION_TOKEN_BYTES: 32,
  EMAIL_VERIFY_EXPIRY: '24h',
  PASSWORD_RESET_EXPIRY: '1h',
} as const;
